export const WORD_LENGTH = 5
export const MAX_ATTEMPTS = 6

export const TILE_REVEAL_DELAY_MS = 160
export const TILE_FLIP_DURATION_MS = 650

export const BOARD_REVEAL_DURATION_MS =
  (WORD_LENGTH - 1) * TILE_REVEAL_DELAY_MS +
  TILE_FLIP_DURATION_MS

export const TILE_WIN_DELAY_MS = 100
export const TILE_WIN_DURATION_MS = 650

export const WIN_CELEBRATION_DURATION_MS =
  (WORD_LENGTH - 1) * TILE_WIN_DELAY_MS +
  TILE_WIN_DURATION_MS